forum/urls.py
from django.conf.urls.defaults import *
from forum.models import Category
from forum.feeds import RssFeed, AtomFeed
        
category_dict = { 
    'queryset': Category.objects.all(),
}

feeds = { 
    'rss': RssFeed,
    'atom': AtomFeed,
}

urlpatterns = patterns('django.views.generic.list_detail',
    (r'^$', 'object_list', category_dict),
)

urlpatterns += patterns('',
    (r'^rss/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds, 'url': 'rss'}),
    (r'^atom/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds, 'url': 'atom'}),
)

urlpatterns += patterns('forum.views',
    (r'^topics/$', 'topic_list'),
    (r'^posts/$', 'post_list'),
    (r'^topic/(?P<topic_id>\d+)/$', 'post_list'),
    (r'^topic/(?P<topic_id>\d+)/create/$', 'post_form'),
    (r'^(?P<slug>[-\w]+)/$', 'topic_list'),
    (r'^(?P<slug>[-\w]+)/create/$', 'topic_form'),
)

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from published_manager.managers import PublishedManager
from django.utils.translation import ugettext as _

class Category(models.Model):
    """
    A forum's category 

    >>> # Create a category
    >>> c = Category.objects.create(name='a')
    >>> c.save()
    """
    name = models.CharField(maxlength=255, verbose_name=_("Category Name"))
    order = models.PositiveIntegerField(default=0, verbose_name=_("Ordering"))
    pub_date = models.DateTimeField(auto_now_add = True, verbose_name=_("Date Published"))

    def __str__(self):
        return _(self.name)

    class Meta:
        ordering = ['order', 'pub_date']
        get_latest_by = "pub_date"
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    class Admin:
        date_hierarchy = 'pub_date'
        ordering = ['order', 'pub_date']
        search_fields = ['name']
        list_display = ['name']

class Forum(models.Model):
    """
    A forum

    >>> # Create a category
    >>> c = Category.objects.create(name='a')
    >>> c.save()
    >>> # Create a forum
    >>> f = Forum.objects.create(category=c, name='a', slug='a', description='a')
    >>> f.save()
    """
    category = models.ForeignKey(Category, verbose_name=_("Category"))
    name = models.CharField(maxlength=255, verbose_name=_("Forum Name"))
    slug = models.SlugField(prepopulate_from=('name',), unique=True, verbose_name=_("Slug Field"))
    description = models.CharField(maxlength=255, verbose_name=_("Forum Description"))
    order = models.PositiveIntegerField(default=0, verbose_name=_("Ordering"))
    pub_date = models.DateTimeField(auto_now_add = True, verbose_name=_("Date Published"))

    def get_absolute_url(self):
        return "/forum/%s/" % self.slug

    def __str__(self):
        return _(self.name)

    class Meta:
        ordering = ['order', 'pub_date']
        get_latest_by = "pub_date"
        verbose_name = _("Forum")
        verbose_name_plural = _("Forums")

    class Admin:
        date_hierarchy = 'pub_date'
        list_display = ('name', 'description')
        ordering = ['order', 'pub_date']
        search_fields = ['name', 'description']
        fields = ( 
            (None, {
                'fields': ('name', 'category', 'description', 'order')
            }),
            (_('Advanced settings'), {
                'classes': 'collapse',
                'fields' : ('slug', 'pub_date')
            }),
        )

class Topic(models.Model):
    """
    A topic 

    >>> # Create a category
    >>> c = Category.objects.create(name='a')
    >>> c.save()
    >>> # Create a forum
    >>> f = Forum.objects.create(category=c, name='a', slug='b', description='a')
    >>> f.save()
    >>> # Create a user
    >>> from django.contrib.auth.models import User
    >>> u = User.objects.create(username='b', password='b')
    >>> u.save()
    >>> # Create a topic 
    >>> t = Topic.objects.create(forum=f, name='a', user=u, ip_address='127.0.0.1', slug='a')
    >>> t.save()
    """
    forum = models.ForeignKey(Forum, verbose_name=_("Forum"))
    name = models.CharField(maxlength=255, verbose_name=_("Topic Name"))
    user = models.ForeignKey(User, verbose_name=_("Author"))
    sticky = models.BooleanField(blank=True, default=False, verbose_name=_("Sticky?"), help_text=_("Makes your topic stick to the top of the forum topic list."))
    locked = models.BooleanField(blank=True, default=False, verbose_name=_("Locked?"), help_text=_("Makes your topic locked so that no new posts can be added."))
    pub_date = models.DateTimeField(auto_now_add = True, verbose_name=_("Date Published"))
    ip_address = models.IPAddressField(verbose_name=_("Author's IP Address"))
    state = models.CharField(maxlength=1, choices=settings.STATE_CHOICES, default=settings.STATE_DEFAULT, verbose_name=_("State of object"))
    slug = models.SlugField(prepopulate_from=('name',), unique=True, verbose_name=_("Slug Field"))
    objects = models.Manager()
    published_objects = PublishedManager()

    def get_absolute_url(self):
        return "/forum/topic/%d/" % self.id

    def __str__(self):
        return _(self.name)

    class Meta:
        ordering = ['sticky', 'pub_date']
        get_latest_by = "pub_date"
        verbose_name = _("Topic")
        verbose_name_plural = _("Topics")

    class Admin:
        date_hierarchy = 'pub_date'
        list_display = ('name', 'user', 'forum')
        ordering = ['sticky', 'pub_date']
        search_fields = ['name']
        fields = ( 
            (None, {
                'fields': ('name', 'user', 'forum', 'state', 'ip_address')
            }),
            (_('Options'), {
                'fields': ('sticky', 'locked')
            }),
            (_('Advanced settings'), {
                'classes': 'collapse',
                'fields': ('slug', 'pub_date')
            }),
        )

class Post(models.Model):
    """
    A post 

    >>> # Create a category
    >>> c = Category.objects.create(name='a')
    >>> c.save()
    >>> # Create a forum
    >>> f = Forum.objects.create(category=c, name='a', slug='c', description='a')
    >>> f.save()
    >>> # Create a user
    >>> from django.contrib.auth.models import User
    >>> u = User.objects.create(username='c', password='c')
    >>> u.save()
    >>> # Create a topic 
    >>> t = Topic.objects.create(forum=f, name='a', user=u, ip_address='127.0.0.1', slug='b')
    >>> t.save()
    >>> # Create a post 
    >>> p = Post.objects.create(topic=t, title='a', text='a', user=u, ip_address='127.0.0.1')
    >>> p.save()
    """
    topic = models.ForeignKey(Topic, verbose_name=_("Topic"))
    title = models.CharField(maxlength=255, verbose_name=_("Post Title"))
    text = models.TextField(verbose_name=_("Post Content"))
    user = models.ForeignKey(User, verbose_name=_("Author"))
    pub_date = models.DateTimeField(auto_now_add = True, verbose_name=_("Date Published"))
    mod_date = models.DateTimeField(auto_now = True, verbose_name=_("Date Modified"))
    ip_address = models.IPAddressField(verbose_name=_("Author's IP Address"))
    state = models.CharField(maxlength=1, choices=settings.STATE_CHOICES, default=settings.STATE_DEFAULT, verbose_name=_("State of object"))
    objects = models.Manager()
    published_objects = PublishedManager()

    def get_absolute_url(self):
        return "/forum/topic/%d/#post_%d" % (self.topic.id, self.id)

    def __str__(self):
        return _(self.text)

    class Meta:
        ordering = ['pub_date']
        get_latest_by = "pub_date"
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    class Admin:
        date_hierarchy = 'pub_date'
        list_display = ('title', 'text', 'user', 'topic')
        ordering = ['pub_date']
        search_fields = ['title', 'text']
        fields = ( 
            (None, {
                'fields': ('title', 'text', 'user', 'topic', 'state', 'ip_address')
            }),
            (_('Advanced settings'), {
                'classes': 'collapse',
                'fields' : ('pub_date', 'mod_date')
            }),
        )

forum/templates/forum/category_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Forums" %}{% endblock %}
{% block breadcrumb %}<li class="last">{% trans "Forums" %}</li>{% endblock %}
{% block content %}
    {% for category in object_list %}
	    <h1>{% blocktrans %}{{ category }}{% endblocktrans %}</h1>
    	{% for forum in category.forum_set.all %}
	    	<a href="{{ forum.get_absolute_url }}">{% blocktrans %}{{ forum }}{% endblocktrans %}</a> {% blocktrans with forum.description as description %}{{ description }}{% endblocktrans %}
    	{% endfor %}
    {% endfor %}
{% endblock %}

forum/templates/forum/forum_topic_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% blocktrans with forum|title as forum_title %}{{ forum_title }} Topics{% endblocktrans %}{% endblock %}
{% block breadcrumb %}<li><a href="/forum/">{% trans "Forum" %}</a></li> <li class="last">{% blocktrans with forum|title as forum_title %}{{ forum_title }}{% endblocktrans %}</li>{% endblock %}
{% block content %}
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
<br /><a href="{{ forum.get_absolute_url }}create/">{% trans "Add New Topic" %}</a>
<table>
<tr><td>{% trans "Topic" %}</td> <td>{% trans "User" %}</td> <td>{% trans "Date Published" %}</td></tr>
{% for object in object_list %}
<tr><td>{% if object.locked %}{% trans "Locked" %}{% endif %}{% if object.sticky %}{% trans "Sticky" %}{% endif %}<a href="{{ object.get_absolute_url }}">{% blocktrans with object.name|title as object_title %}{{ object_title }}{% endblocktrans %}</a></td> <td><a href="{{ object.user.get_absolute_url }}">{{ object.user }}</a>{% load iptocountry_filter %}{{ object.ip_address|get_country2:"iptocountry/flags/"}}</td> <td>{{ object.pub_date|date:"F j Y" }}</td></tr>
{% endfor %}
</table>
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% endblock %}

forum/templates/forum/post_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Forums" %}{% endblock %}
{% block extrahead %}
{% load adminmedia %}<script type="text/javascript" src="{% admin_media_prefix %}js/urlify.js"></script>
{% endblock %}
{% block breadcrumb %}<li><a href="/forums/">{% trans "Forums" %}</a></li> <li><a href="{{ topic.forum.get_absolute_url }}">{% blocktrans with topic.forum|title as forum_title %}{{ forum_title }}{% endblocktrans %}</a></li> <li><a href="{{ topic.get_absolute_url }}">{% blocktrans with topic|title as topic_title %}{{ topic_title }}{% endblocktrans %}</a></li><li class="last">{% trans "New Topic" %}</li>{% endblock %}
{% block content %}
{% if form.has_errors %}
<h2>{% blocktrans count form.errors as counter %}
Please correct the following error.
{% plural %}
Please correct the following errors.
{% endblocktrans %}:</h2>
{{ form.errors }}
{% endif %}

<form method="post" action=".">
<input type="hidden" id="id_topic" class="vSelectField required" name="topic" size="1" value="{{ topic.id }}">
<input type="hidden" id="id_user" class="vSelectField required" name="user" value="{{ user.id }}">
<input type="hidden" id="id_state" class="vSelectField required" name="state" value="{{ STATE_DEFAULT  }}">
<input type="hidden" id="id_ip_address" class="vIPAddressField required" name="ip_address" size="15" value="{{ request.META.REMOTE_ADDR }}" maxlength="15" />
<input type="hidden" id="id_slug" class="vTextField" name="slug" value="" />
<p><label for="id_title">{% trans "Title" %}:</label> {{ form.title }}
{% if form.title.errors %}*** {% blocktrans %}{{ form.title.errors|join:", " }}{% endblocktrans %}{% endif %}</p>
<p><label for="id_text">{% trans "Text" %}:</label> {{ form.text }}
{% if form.text.errors %}*** {% blocktrans %}{{ form.text.errors|join:", " }}{% endblocktrans %}{% endif %}</p>
<input value="{% blocktrans %}New Post{% endblocktrans %}" type="submit" />
</form>
<script type="text/javascript">
        document.getElementById("id_slug").onchange = function() { this._changed = true; };document.getElementById("id_title").onkeyup = function() { var e = document.getElementById("id_slug"); if(!e._changed) { e.value = URLify(document.getElementById("id_title").value, 50);} }; 
</script>
{% endblock %}

forum/templates/forum/post_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% blocktrans %}{{ topic.forum|title }} {{ topic|title }}{% endblocktrans %}{% endblock %}
{% block breadcrumb %}<li><a href="/forum/">{% trans "Forum" %}</a></li> <li><a href="{{ topic.forum.get_absolute_url }}">{% blocktrans %}{{ topic.forum|title }}{% endblocktrans %}</a></li> <li class="last">{% blocktrans %}{{ topic|title }}{% endblocktrans %}</li>{% endblock %}
{% block content %}
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% if not topic.locked %}
<a href="{{ topic.get_absolute_url }}create/">{% trans "Add New Post" %}</a>
{% endif %}
<table>
{% load sorter %}
<tr><td>{% sorter "topic" "Topic" %}</td> <td>{% sorter "user" "User" %}</td> <td>{% sorter "pub_date" "Date Published" %}</td> <td>{% sorter "text" "Post" %}</td></tr>
{% for object in object_list %}
<tr><td><a href="{{ object.topic.get_absolute_url }}">{% blocktrans %}{{ object.topic }}{% endblocktrans %}</a></td> <td><img src="{{ post.user.get_profile.get_avatar_url }}" /><a href="{{ object.user.get_absolute_url }}">{{ object.user }}</a>{% load iptocountry_filter %}{{ object.ip_address|get_country2:"iptocountry/flags/"}}</td> <td>{{ object.pub_date|date:"F j Y" }}</td> <td><a name="post_{{ object.id }}" /><a href="{{ object.get_absolute_url }}">{% blocktrans %}{{ object.text }}{% endblocktrans %}</a></td></tr>
{% endfor %}
</table>
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% endblock %}

forum/templates/forum/topic_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Forums" %}{% endblock %}
{% block extrahead %}
{% load adminmedia %}<script type="text/javascript" src="{% admin_media_prefix %}js/urlify.js"></script>
{% endblock %}
{% block breadcrumb %}<li><a href="/forums/">{% trans "Forums" %}</a></li> <li><a href="{{ forum.get_absolute_url }}">{% blocktrans with forum|title as forum_title %}{{ forum_title }}{% endblocktrans %}</a></li> <li class="last">{% trans "New Topic" %}</li>{% endblock %}
{% block content %}
{% if form.has_errors %}
<h2>{% blocktrans count form.errors as counter %}
Please correct the following error.
{% plural %}
Please correct the following errors.
{% endblocktrans %}:</h2>
{{ form.errors }}
{% endif %}

<form method="post" action=".">
<input type="hidden" id="id_forum" class="vSelectField required" name="forum" size="1" value="{{ forum.id }}">
<input type="hidden" id="id_user" class="vSelectField required" name="user" value="{{ user.id }}">
<input type="hidden" id="id_state" class="vSelectField required" name="state" value="{{ STATE_DEFAULT  }}">
<input type="hidden" id="id_sticky" class="vCheckboxField" name="sticky" value="off" />
<input type="hidden" id="id_locked" class="vCheckboxField" name="locked" value="off" />
<input type="hidden" id="id_ip_address" class="vIPAddressField required" name="ip_address" size="15" value="{{ request.META.REMOTE_ADDR }}" maxlength="15" />
<input type="hidden" id="id_slug" class="vTextField" name="slug" value="" />
<p><label for="id_name">{% trans "Name" %}:</label> {{ form.name }}
{% if form.name.errors %}*** {% blocktrans %}{{ form.name.errors|join:", " }}{% endblocktrans %}{% endif %}</p>
<input value="{% blocktrans %}New Topic{% endblocktrans %}" type="submit" />
</form>
<script type="text/javascript">
        document.getElementById("id_slug").onchange = function() { this._changed = true; };document.getElementById("id_name").onkeyup = function() { var e = document.getElementById("id_slug"); if(!e._changed) { e.value = URLify(document.getElementById("id_name").value, 50);} }; 
</script>
{% endblock %}

forum/templates/forum/topic_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Forum Topics" %}{% endblock %}
{% block breadcrumb %}<li><a href="/forum/">{% trans "Forum" %}</a></li> <li class="last">{% trans "Topics" %}</li>{% endblock %}
{% block content %}
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
<table>
{% load sorter %}
<tr><td>{% sorter "name" "Topic" %}</td> <td>{% sorter "forum" "Forum" %}</td> <td>{% sorter "user" "User" %}</td> <td>{% sorter "pub_date" "Date Published" %}</td></tr>
{% for object in object_list %}
<tr><td><a href="{{ object.get_absolute_url }}">{% blocktrans %}{{ object.name|title }}{% endblocktrans %}</a></td> <td><a href="{{ object.forum.get_absolute_url }}">{% blocktrans %}{{ object.forum|title }}{% endblocktrans %}</a></td> <td><a href="{{ object.user.get_absolute_url }}">{{ object.user }}</a>{% load iptocountry_filter %}{{ object.ip_address|get_country2:"iptocountry/flags/"}}</td> <td>{{ object.pub_date|date:"F j Y" }}</td></tr>
{% endfor %}
</table>
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% endblock %}

forum/templates/forum/topic_post_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% blocktrans with topic.forum|title as forum_title and topic|title as topic_title %}{{ forum_title }} {{ topic_title }}{% endblocktrans %}{% endblock %}
{% block breadcrumb %}<li><a href="/forum/">{% trans "Forum" %}</a></li> <li><a href="{{ topic.forum.get_absolute_url }}">{% blocktrans with topic.forum|title as forum_title %}{{ forum_title }}{% endblocktrans %}</a></li> <li class="last">{% blocktrans with topic|title as topic_title %}{{ topic_title }}{% endblocktrans %}</li>{% endblock %}
{% block content %}
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% if not topic.locked %}
<a href="{{ topic.get_absolute_url }}create/">{% trans "Add New Post" %}</a>
{% endif %}
<table>
<tr><td>{% trans "User" %}</td> <td>{% trans "Date Published" %}</td> <td>{% trans "Post" %}</td></tr>
{% for object in object_list %}
<tr><td><img src="{{ post.user.get_profile.get_avatar_url }}" /><a href="{{ object.user.get_absolute_url }}">{{ object.user }}</a>{% load iptocountry_filter %}{{ object.ip_address|get_country2:"iptocountry/flags/"}}</td> <td>{{ object.pub_date|date:"F j Y" }}</td> <td>{% blocktrans with object.text as object_text %}{{ object_text }}{% endblocktrans %}<a name="post_{{ object.id }}" /></td></tr>
{% endfor %}
</table>
{% if is_paginated %}{% load paginator %}<div class="paginator">{% paginator %}</div>{% endif %}
{% endblock %}